// Code generated by sqlgen. DO NOT EDIT.

package uint8

import (
	"github.com/si3nloong/sqlgen/sequel"
	"github.com/si3nloong/sqlgen/sequel/encoding"
)

func (Model) TableName() string {
	return "model"
}
func (Model) HasPK() {}
func (v *Model) SetPK(val uint8) {
	v.ID = val
}
func (Model) IsAutoIncr() {}
func (v *Model) ScanAutoIncr(val int64) error {
	v.ID = uint8(val)
	return nil
}
func (v Model) PK() (string, int, any) {
	return "id", 0, (int64)(v.ID)
}
func (Model) Columns() []string {
	return []string{"id"} // 1
}
func (v Model) Values() []any {
	return []any{
		(int64)(v.ID), // 0 - id
	}
}
func (v *Model) Addrs() []any {
	return []any{
		encoding.Uint8Scanner[uint8](&v.ID), // 0 - id
	}
}
func (v Model) FindOneByPKStmt() (string, []any) {
	return "SELECT `id` FROM `model` WHERE `id` = ? LIMIT 1;", []any{(int64)(v.ID)}
}
func (v Model) IDValue() any {
	return (int64)(v.ID)
}
func (v Model) ColumnID() sequel.ColumnConvertClause[uint8] {
	return sequel.Column("id", v.ID, convertUint8ToValue)
}

func convertUint8ToValue(val uint8) any {
	return (int64)(val)
}
