// Code generated by sqlgen, version 1.0.0. DO NOT EDIT.

package imported

import (
	"database/sql"
	"database/sql/driver"
)

func (Model) Table() string {
	return "model"
}

func (Model) Columns() []string {
	return []string{"str", "bool", "bytes", "int_16", "int_32", "int_64", "time"}
}

func (v Model) Values() []any {
	return []any{(driver.Valuer)(v.Str), (driver.Valuer)(v.Bool), v.Bytes, (driver.Valuer)(v.Int16), (driver.Valuer)(v.Int32), (driver.Valuer)(v.Int64), (driver.Valuer)(v.Time)}
}

func (v *Model) Addrs() []any {
	return []any{(sql.Scanner)(&v.Str), (sql.Scanner)(&v.Bool), &v.Bytes, (sql.Scanner)(&v.Int16), (sql.Scanner)(&v.Int32), (sql.Scanner)(&v.Int64), (sql.Scanner)(&v.Time)}
}

func (Some) Table() string {
	return "some"
}

func (Some) Columns() []string {
	return []string{"id"}
}

func (v Some) Values() []any {
	return []any{(driver.Valuer)(v.ID)}
}

func (v *Some) Addrs() []any {
	return []any{(sql.Scanner)(&v.ID)}
}
