// Code generated by sqlgen, version 1.0.0. DO NOT EDIT.

package valuer

import (
	"database/sql/driver"
)

// Implements `sql.Valuer` interface.
func (B) Table() string {
	return "b"
}

func (B) Columns() []string {
	return []string{"id", "value", "n"}
}

func (v B) Values() []any {
	return []any{v.ID, (driver.Valuer)(v.Value), v.N}
}

func (v *B) Addrs() []any {
	return []any{&v.ID, &v.Value, &v.N}
}
