version: 2
updates:
  - package-ecosystem: "gomod"
    target-branch: "dev"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    target-branch: "dev"
    directory: "/"
    schedule:
      interval: "daily"
