// Code generated by sqlgen, version 1.0.0. DO NOT EDIT.

package embedded

import (
	"github.com/si3nloong/sqlgen/sql/types"
)

// Implements `sql.Valuer` interface.
func (B) Table() string {
	return "b"
}

func (B) Columns() []string {
	return []string{"name", "id", "name", "z"}
}

func (v B) Values() []any {
	return []any{string(v.Name), int64(v.ID), string(v.Name), bool(v.Z)}
}

func (v *B) Addrs() []any {
	return []any{types.String(&v.Name), types.Integer(&v.ID), types.String(&v.Name), types.Bool(&v.Z)}
}

// Implements `sql.Valuer` interface.
func (a) Table() string {
	return "a"
}

func (a) Columns() []string {
	return []string{"id", "name", "z"}
}

func (v a) Values() []any {
	return []any{int64(v.ID), string(v.Name), bool(v.Z)}
}

func (v *a) Addrs() []any {
	return []any{types.Integer(&v.ID), types.String(&v.Name), types.Bool(&v.Z)}
}
