# Where are all the model files located? globs are supported eg  src/**/*.go
src:
  - ./examples/testcase/schema/table-name/**/*

# Optional:
driver: mysql

# Optional:
naming_convention: snake_case

# Optional:
struct_tag: sql

# Optional:
skip_escape: false

# Optional: Where should any generated code go?
exec:
  skip_empty: false
  filename: generated.go

# Optional:
database:
  dir: db
  package: db
  filename: db.go

# Optional:
strict: true

# Optional:
skip_header: false

# Optional:
source_map: false
# Optional: set to skip running `go mod tidy` when generating server code
# skip_mod_tidy: false
