// Code generated by sqlgen. DO NOT EDIT.

package main

import (
	"github.com/google/uuid"
	"github.com/si3nloong/sqlgen/sequel"
)

func (User) TableName() string {
	return "user"
}
func (User) Columns() []string {
	return []string{"id", "name"} // 2
}
func (v User) Values() []any {
	return []any{
		v.ID,   // 0 - id
		v.Name, // 1 - name
	}
}
func (v *User) Addrs() []any {
	return []any{
		&v.ID,   // 0 - id
		&v.Name, // 1 - name
	}
}
func (User) SQLInsertPlaceholders(row int) string {
	return "(?,?)" // 2
}
func (v User) InsertOneStmt() (string, []any) {
	return "INSERT INTO `user` (`id`,`name`) VALUES (?,?);", v.Values()
}
func (v User) IDValue() any {
	return v.ID
}
func (v User) NameValue() any {
	return v.Name
}
func (v User) ColumnID() sequel.ColumnClause[uuid.UUID] {
	return sequel.ValueColumn("id", v.ID)
}
func (v User) ColumnName() sequel.ColumnClause[string] {
	return sequel.PrimitiveColumn("name", v.Name)
}
