// Code generated by sqlgen, version v1.0.0-beta. DO NOT EDIT.

package tablename

import (
	"github.com/si3nloong/sqlgen/sequel/types"
)

func (CustomTableName1) CreateTableStmt() string {
	return "CREATE TABLE IF NOT EXISTS `custom_table_name_1` (`text` VARCHAR(255) NOT NULL);"
}
func (CustomTableName1) AlterTableStmt() string {
	return "ALTER TABLE `custom_table_name_1` MODIFY `text` VARCHAR(255) NOT NULL;"
}
func (CustomTableName1) TableName() string {
	return "`custom_table_name_1`"
}
func (CustomTableName1) Columns() []string {
	return []string{"`text`"}
}
func (v CustomTableName1) Values() []any {
	return []any{string(v.Text)}
}
func (v *CustomTableName1) Addrs() []any {
	return []any{types.String(&v.Text)}
}

func (CustomTableName2) CreateTableStmt() string {
	return "CREATE TABLE IF NOT EXISTS `custom_table_2` (`text` VARCHAR(255) NOT NULL);"
}
func (CustomTableName2) AlterTableStmt() string {
	return "ALTER TABLE `custom_table_2` MODIFY `text` VARCHAR(255) NOT NULL;"
}
func (CustomTableName2) TableName() string {
	return "`custom_table_2`"
}
func (CustomTableName2) Columns() []string {
	return []string{"`text`"}
}
func (v CustomTableName2) Values() []any {
	return []any{string(v.Text)}
}
func (v *CustomTableName2) Addrs() []any {
	return []any{types.String(&v.Text)}
}

func (CustomTableName3) CreateTableStmt() string {
	return "CREATE TABLE IF NOT EXISTS `custom_table3` (`text` VARCHAR(255) NOT NULL);"
}
func (CustomTableName3) AlterTableStmt() string {
	return "ALTER TABLE `custom_table3` MODIFY `text` VARCHAR(255) NOT NULL;"
}
func (CustomTableName3) TableName() string {
	return "`custom_table3`"
}
func (CustomTableName3) Columns() []string {
	return []string{"`text`"}
}
func (v CustomTableName3) Values() []any {
	return []any{string(v.Text)}
}
func (v *CustomTableName3) Addrs() []any {
	return []any{types.String(&v.Text)}
}
