// Code generated by sqlgen, version 1.0.0. DO NOT EDIT.

package valuer

import (
	"database/sql/driver"

	"github.com/si3nloong/sqlgen/sql/types"
)

// Implements `sql.Valuer` interface.
func (B) Table() string {
	return "b"
}

func (B) Columns() []string {
	return []string{"id", "value", "n"}
}

func (v B) Values() []any {
	return []any{int64(v.ID), (driver.Valuer)(v.Value), string(v.N)}
}

func (v *B) Addrs() []any {
	return []any{types.Integer(&v.ID), &v.Value, types.String(&v.N)}
}
