// Code generated by sqlgen. DO NOT EDIT.

package size

import (
	"time"

	"github.com/si3nloong/sqlgen/sequel"
)

func (Size) TableName() string {
	return "size"
}
func (Size) Columns() []string {
	return []string{"str", "timestamp", "time"} // 3
}
func (v Size) Values() []any {
	return []any{
		v.Str,       // 0 - str
		v.Timestamp, // 1 - timestamp
		v.Time,      // 2 - time
	}
}
func (v *Size) Addrs() []any {
	return []any{
		&v.Str,       // 0 - str
		&v.Timestamp, // 1 - timestamp
		&v.Time,      // 2 - time
	}
}
func (Size) InsertPlaceholders(row int) string {
	return "(?,?,?)" // 3
}
func (v Size) InsertOneStmt() (string, []any) {
	return "INSERT INTO `size` (`str`,`timestamp`,`time`) VALUES (?,?,?);", v.Values()
}
func (v Size) StrValue() any {
	return v.Str
}
func (v Size) TimestampValue() any {
	return v.Timestamp
}
func (v Size) TimeValue() any {
	return v.Time
}
func (v Size) ColumnStr() sequel.ColumnClause[string] {
	return sequel.BasicColumn("str", v.Str)
}
func (v Size) ColumnTimestamp() sequel.ColumnClause[time.Time] {
	return sequel.BasicColumn("timestamp", v.Timestamp)
}
func (v Size) ColumnTime() sequel.ColumnClause[time.Time] {
	return sequel.BasicColumn("time", v.Time)
}
