// Code generated by sqlgen, version 1.0.0. DO NOT EDIT.

package alias

import (
	"github.com/si3nloong/sqlgen/sql/types"
)

// Implements `sql.Valuer` interface.
func (AliasStruct) Table() string {
	return "alias_struct"
}

func (AliasStruct) Columns() []string {
	return []string{"header", "text", "created"}
}

func (v AliasStruct) Values() []any {
	return []any{string(v.Header), string(v.Text), v.Created}
}

func (v *AliasStruct) Addrs() []any {
	return []any{types.String(&v.Header), types.String(&v.Text), &v.Created}
}
