// Code generated by sqlgen. DO NOT EDIT.

package embedded

import (
	"cloud.google.com/go/civil"
	"github.com/si3nloong/sqlgen/sequel"
)

func (B) TableName() string {
	return "b"
}
func (B) Columns() []string {
	return []string{"date", "time"} // 2
}
func (v B) Values() []any {
	return []any{
		v.DateTime.Date, // 0 - date
		v.DateTime.Time, // 1 - time
	}
}
func (v *B) Addrs() []any {
	return []any{
		&v.DateTime.Date, // 0 - date
		&v.DateTime.Time, // 1 - time
	}
}
func (B) SQLInsertPlaceholders(row int) string {
	return "(?,?)" // 2
}
func (v B) InsertOneStmt() (string, []any) {
	return "INSERT INTO `b` (`date`,`time`) VALUES (?,?);", v.Values()
}
func (v B) DateValue() any {
	return v.DateTime.Date
}
func (v B) TimeValue() any {
	return v.DateTime.Time
}
func (v B) ColumnDate() sequel.ColumnClause[civil.Date] {
	return sequel.ValueColumn("date", v.DateTime.Date)
}
func (v B) ColumnTime() sequel.ColumnClause[civil.Time] {
	return sequel.ValueColumn("time", v.DateTime.Time)
}
