// Code generated by sqlgen. DO NOT EDIT.

package date

import (
	"cloud.google.com/go/civil"
	"github.com/google/uuid"
	"github.com/si3nloong/sqlgen/sequel"
)

func (User) TableName() string {
	return "user"
}
func (User) HasPK() {}
func (v *User) SetPK(val uuid.UUID) {
	v.ID = val
}
func (v User) PK() (string, int, any) {
	return "id", 0, v.ID
}
func (User) Columns() []string {
	return []string{"id", "birth_date"} // 2
}
func (v User) Values() []any {
	return []any{
		v.ID,        // 0 - id
		v.BirthDate, // 1 - birth_date
	}
}
func (v *User) Addrs() []any {
	return []any{
		&v.ID,        // 0 - id
		&v.BirthDate, // 1 - birth_date
	}
}
func (User) SQLInsertPlaceholders(row int) string {
	return "(?,?)" // 2
}
func (v User) InsertOneStmt() (string, []any) {
	return "INSERT INTO `user` (`id`,`birth_date`) VALUES (?,?);", v.Values()
}
func (v User) FindOneByPKStmt() (string, []any) {
	return "SELECT `id`,`birth_date` FROM `user` WHERE `id` = ? LIMIT 1;", []any{v.ID}
}
func (v User) UpdateOneByPKStmt() (string, []any) {
	return "UPDATE `user` SET `birth_date` = ? WHERE `id` = ?;", []any{v.BirthDate, v.ID}
}
func (v User) IDValue() any {
	return v.ID
}
func (v User) BirthDateValue() any {
	return v.BirthDate
}
func (v User) ColumnID() sequel.ColumnClause[uuid.UUID] {
	return sequel.ValueColumn("id", v.ID)
}
func (v User) ColumnBirthDate() sequel.ColumnClause[civil.Date] {
	return sequel.ValueColumn("birth_date", v.BirthDate)
}
