// Code generated by sqlgen, version 1.0.0. DO NOT EDIT.

package pointer

// Implements `sql.Valuer` interface.
func (Ptr) Table() string {
	return "ptr"
}

func (Ptr) Columns() []string {
	return []string{"str", "bytes", "bool", "int", "int_8", "int_16", "int_32", "int_64", "uint", "uint_8", "uint_16", "uint_32", "uint_64", "f_32", "f_64", "time"}
}

func (v Ptr) Values() []any {
	return []any{v.Str, v.Bytes, v.Bool, v.Int, v.Int8, v.Int16, v.Int32, v.Int64, v.Uint, v.Uint8, v.Uint16, v.Uint32, v.Uint64, v.F32, v.F64, v.Time}
}

func (v *Ptr) Addrs() []any {
	return []any{&v.Str, &v.Bytes, &v.Bool, &v.Int, &v.Int8, &v.Int16, &v.Int32, &v.Int64, &v.Uint, &v.Uint8, &v.Uint16, &v.Uint32, &v.Uint64, &v.F32, &v.F64, &v.Time}
}
