// Code generated by sqlgen, version v1.0.0-beta.1; DO NOT EDIT.

package imported

import (
	"time"

	"github.com/si3nloong/sqlgen/sequel"
	"github.com/si3nloong/sqlgen/sequel/encoding"
)

func (ImportedEnum) TableName() string {
	return "imported_enum"
}
func (ImportedEnum) Columns() []string {
	return []string{"weekday"} // 1
}
func (v ImportedEnum) Values() []any {
	return []any{
		(int64)(v.Weekday), // 0 - weekday
	}
}
func (v *ImportedEnum) Addrs() []any {
	return []any{
		encoding.IntScanner[time.Weekday](&v.Weekday), // 0 - weekday
	}
}
func (ImportedEnum) InsertPlaceholders(row int) string {
	return "(?)" // 1
}
func (v ImportedEnum) InsertOneStmt() (string, []any) {
	return "INSERT INTO `imported_enum` (`weekday`) VALUES (?);", v.Values()
}
func (v ImportedEnum) WeekdayValue() any {
	return (int64)(v.Weekday)
}
func (v ImportedEnum) ColumnWeekday() sequel.ColumnConvertClause[time.Weekday] {
	return sequel.Column("weekday", v.Weekday, func(val time.Weekday) any {
		return (int64)(val)
	})
}
