// Code generated by "stringer --type indexType --linecomment"; DO NOT EDIT.

package postgres

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[bTree-0]
	_ = x[hash-1]
	_ = x[brin-2]
}

const _indexType_name = "BTREEHASHBRIN"

var _indexType_index = [...]uint8{0, 5, 9, 13}

func (i indexType) String() string {
	if i >= indexType(len(_indexType_index)-1) {
		return "indexType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _indexType_name[_indexType_index[i]:_indexType_index[i+1]]
}
