// Code generated by sqlgen, version 1.0.0. DO NOT EDIT.

package autopk

import (
	"github.com/si3nloong/sqlgen/sql/types"
)

func (Model) Table() string {
	return "model"
}
func (Model) Columns() []string {
	return []string{"name", "f", "id", "n"}
}
func (Model) IsAutoIncr() bool {
	return true
}
func (v Model) PK() (string, int, any) {
	return "id", 2, int64(v.ID)
}

func (v Model) Values() []any {
	return []any{string(v.Name), bool(v.F), int64(v.ID), v.N}
}
func (v *Model) Addrs() []any {
	return []any{types.String(&v.Name), types.Bool(&v.F), types.Integer(&v.ID), &v.N}
}
