// Code generated by sqlgen, version 1.0.0. DO NOT EDIT.

package array

import (
	"database/sql"
	"database/sql/driver"

	"github.com/si3nloong/sqlgen/sql/types"
)

// Implements `sql.Valuer` interface.
func (Address) Table() string {
	return "address"
}

func (Address) Columns() []string {
	return []string{"line_1", "line_2", "city", "post_code", "state_code", "country_code"}
}

func (v Address) Values() []any {
	return []any{string(v.Line1), (driver.Valuer)(v.Line2), string(v.City), int64(v.PostCode), string(v.StateCode), string(v.CountryCode)}
}

func (v *Address) Addrs() []any {
	return []any{types.String(&v.Line1), (sql.Scanner)(&v.Line2), types.String(&v.City), types.Integer(&v.PostCode), types.String(&v.StateCode), types.String(&v.CountryCode)}
}

// Implements `sql.Valuer` interface.
func (Customer) Table() string {
	return "customer"
}

func (Customer) Columns() []string {
	return []string{"id", "howOld", "name", "address", "nicknames", "status", "join_at"}
}

func (v Customer) Values() []any {
	return []any{int64(v.ID), int64(v.Age), (driver.Valuer)(v.Name), (driver.Valuer)(v.Address), v.Nicknames, string(v.Status), v.JoinAt}
}

func (v *Customer) Addrs() []any {
	return []any{types.Integer(&v.ID), types.Integer(&v.Age), (sql.Scanner)(&v.Name), &v.Address, &v.Nicknames, types.String(&v.Status), &v.JoinAt}
}
