// Code generated by sqlgen. DO NOT EDIT.

package readonly

import (
	"github.com/si3nloong/sqlgen/sequel"
)

func (Model) TableName() string {
	return "model"
}
func (Model) Columns() []string {
	return []string{"a", "b", "read_only"} // 3
}
func (v *Model) Addrs() []any {
	return []any{
		&v.A,        // 0 - a
		&v.B,        // 1 - b
		&v.ReadOnly, // 2 - read_only
	}
}
func (v Model) ColumnA() sequel.ColumnClause[string] {
	return sequel.BasicColumn("a", v.A)
}
func (v Model) ColumnB() sequel.ColumnClause[bool] {
	return sequel.BasicColumn("b", v.B)
}
func (v Model) ColumnReadOnly() sequel.ColumnClause[string] {
	return sequel.BasicColumn("read_only", v.ReadOnly)
}
