// Code generated by sqlgen, version 1.0.0. DO NOT EDIT.

package valuer

import (
	"database/sql/driver"

	"github.com/si3nloong/sqlgen/sequel/types"
)

func (B) CreateTableStmt() string {
	return "CREATE TABLE IF NOT EXISTS b (id BIGINT NOT NULL,value VARCHAR(255) NOT NULL,n VARCHAR(255) NOT NULL);"
}
func (B) AlterTableStmt() string {
	return "ALTER TABLE b MODIFY id BIGINT NOT NULL,MODIFY value VARCHAR(255) NOT NULL AFTER id,MODIFY n VARCHAR(255) NOT NULL AFTER value;"
}
func (B) TableName() string {
	return "b"
}
func (B) Columns() []string {
	return []string{"id", "value", "n"}
}
func (v B) Values() []any {
	return []any{int64(v.ID), (driver.Valuer)(v.Value), string(v.N)}
}
func (v *B) Addrs() []any {
	return []any{types.Integer(&v.ID), &v.Value, types.String(&v.N)}
}
