// Code generated by sqlgen. DO NOT EDIT.

package readonly

import (
	"github.com/si3nloong/sqlgen/sequel"
)

func (Model) TableName() string {
	return "model"
}
func (Model) Columns() []string {
	return []string{"a", "b", "read_only"} // 3
}
func (v Model) Values() []any {
	return []any{
		v.A,        // 0 - a
		v.B,        // 1 - b
		v.ReadOnly, // 2 - read_only
	}
}
func (v *Model) Addrs() []any {
	return []any{
		&v.A,        // 0 - a
		&v.B,        // 1 - b
		&v.ReadOnly, // 2 - read_only
	}
}
func (Model) SQLInsertColumns() string {
	return "`a`,`b`"
}
func (Model) SQLInsertPlaceholders(row int) string {
	return "(?,?)" // 2
}
func (v Model) InsertOneStmt() (string, []any) {
	return "INSERT INTO `model` (`a`,`b`) VALUES (?,?);", []any{v.A, v.B}
}
func (v Model) AValue() any {
	return v.A
}
func (v Model) BValue() any {
	return v.B
}
func (v Model) ReadOnlyValue() any {
	return v.ReadOnly
}
func (v Model) ColumnA() sequel.ColumnClause[string] {
	return sequel.PrimitiveColumn("a", v.A)
}
func (v Model) ColumnB() sequel.ColumnClause[bool] {
	return sequel.PrimitiveColumn("b", v.B)
}
func (v Model) ColumnReadOnly() sequel.ColumnClause[string] {
	return sequel.PrimitiveColumn("read_only", v.ReadOnly)
}
