// Code generated by sqlgen. DO NOT EDIT.

package enum

import (
	"github.com/si3nloong/sqlgen/sequel"
	"github.com/si3nloong/sqlgen/sequel/encoding"
)

func (Custom) TableName() string {
	return "custom"
}
func (Custom) Columns() []string {
	return []string{"text", "e", "num"} // 3
}
func (v Custom) Values() []any {
	return []any{
		(string)(v.Str), // 0 - text
		(int64)(v.Enum), // 1 - e
		(int64)(v.Num),  // 2 - num
	}
}
func (v *Custom) Addrs() []any {
	return []any{
		encoding.StringScanner[longText](&v.Str), // 0 - text
		encoding.IntScanner[Enum](&v.Enum),       // 1 - e
		encoding.Uint16Scanner[uint16](&v.Num),   // 2 - num
	}
}
func (Custom) InsertPlaceholders(row int) string {
	return "(?,?,?)" // 3
}
func (v Custom) InsertOneStmt() (string, []any) {
	return "INSERT INTO `custom` (`text`,`e`,`num`) VALUES (?,?,?);", v.Values()
}
func (v Custom) StrValue() any {
	return (string)(v.Str)
}
func (v Custom) EnumValue() any {
	return (int64)(v.Enum)
}
func (v Custom) NumValue() any {
	return (int64)(v.Num)
}
func (v Custom) ColumnStr() sequel.ColumnConvertClause[longText] {
	return sequel.Column("text", v.Str, func(val longText) any {
		return (string)(val)
	})
}
func (v Custom) ColumnEnum() sequel.ColumnConvertClause[Enum] {
	return sequel.Column("e", v.Enum, func(val Enum) any {
		return (int64)(val)
	})
}
func (v Custom) ColumnNum() sequel.ColumnConvertClause[uint16] {
	return sequel.Column("num", v.Num, func(val uint16) any {
		return (int64)(val)
	})
}
