// Code generated by sqlgen. DO NOT EDIT.

package enum

import (
	"github.com/si3nloong/sqlgen/sequel"
	"github.com/si3nloong/sqlgen/sequel/encoding"
)

func (Custom) TableName() string {
	return "custom"
}
func (Custom) Columns() []string {
	return []string{"text", "e", "ptr_str", "uint_16", "num"} // 5
}
func (v Custom) Values() []any {
	return []any{
		v.StrValue(),    // 0 - text
		v.EnumValue(),   // 1 - e
		v.PtrStrValue(), // 2 - ptr_str
		v.Uint16Value(), // 3 - uint_16
		(int64)(v.Num),  // 4 - num
	}
}
func (v *Custom) Addrs() []any {
	if v.PtrStr == nil {
		v.PtrStr = new(longText)
	}
	return []any{
		encoding.StringScanner[longText](&v.Str),      // 0 - text
		encoding.IntScanner[Enum](&v.Enum),            // 1 - e
		encoding.JSONScanner(&v.PtrStr),               // 2 - ptr_str
		encoding.Uint16Scanner[uint16Enum](&v.Uint16), // 3 - uint_16
		encoding.Uint16Scanner[uint16](&v.Num),        // 4 - num
	}
}
func (Custom) SQLInsertPlaceholders(row int) string {
	return "(?,?,?,?,?)" // 5
}
func (v Custom) InsertOneStmt() (string, []any) {
	return "INSERT INTO `custom` (`text`,`e`,`ptr_str`,`uint_16`,`num`) VALUES (?,?,?,?,?);", v.Values()
}
func (v Custom) StrValue() any {
	if v.Str == "" {
		return (string)(otherStr)
	}
	return (string)(v.Str)
}
func (v Custom) EnumValue() any {
	if v.Enum == 0 {
		return (int64)(success)
	}
	return (int64)(v.Enum)
}
func (v Custom) PtrStrValue() any {
	if v.PtrStr != nil {
		return (string)(*v.PtrStr)
	}
	return nil
}
func (v Custom) Uint16Value() any {
	return (int64)(v.Uint16)
}
func (v Custom) NumValue() any {
	return (int64)(v.Num)
}
func (v Custom) ColumnStr() sequel.ColumnConvertClause[longText] {
	return sequel.Column("text", v.Str, convertLongTextToValue)
}
func (v Custom) ColumnEnum() sequel.ColumnConvertClause[Enum] {
	return sequel.Column("e", v.Enum, convertEnumToValue)
}
func (v Custom) ColumnPtrStr() sequel.ColumnConvertClause[*longText] {
	return sequel.Column("ptr_str", v.PtrStr, convertPtrlongTextToValue)
}
func (v Custom) ColumnUint16() sequel.ColumnConvertClause[uint16Enum] {
	return sequel.Column("uint_16", v.Uint16, convertUint16EnumToValue)
}
func (v Custom) ColumnNum() sequel.ColumnConvertClause[uint16] {
	return sequel.Column("num", v.Num, convertUint16ToValue)
}

func convertUint16ToValue(val uint16) any {
	return (int64)(val)
}
func convertUint16EnumToValue(val uint16Enum) any {
	return (int64)(val)
}
func convertPtrlongTextToValue(val *longText) any {
	if val != nil {
		return (string)(*val)
	}
	return nil
}
func convertLongTextToValue(val longText) any {
	if val == "" {
		return (string)(otherStr)
	}
	return (string)(val)
}
func convertEnumToValue(val Enum) any {
	if val == 0 {
		return (int64)(success)
	}
	return (int64)(val)
}
