// Code generated by sqlgen. DO NOT EDIT.

package version

import (
	uuid "github.com/gofrs/uuid/v5"
	"github.com/si3nloong/sqlgen/sequel"
)

func (Version) TableName() string {
	return "version"
}
func (Version) HasPK() {}
func (v *Version) SetPK(val uuid.UUID) {
	v.ID = val
}
func (v Version) PK() (string, int, any) {
	return "id", 0, v.ID
}
func (Version) Columns() []string {
	return []string{"id"} // 1
}
func (v Version) Values() []any {
	return []any{
		v.ID, // 0 - id
	}
}
func (v *Version) Addrs() []any {
	return []any{
		&v.ID, // 0 - id
	}
}
func (Version) SQLInsertPlaceholders(row int) string {
	return "(?)" // 1
}
func (v Version) InsertOneStmt() (string, []any) {
	return "INSERT INTO `version` (`id`) VALUES (?);", v.Values()
}
func (v Version) FindOneByPKStmt() (string, []any) {
	return "SELECT `id` FROM `version` WHERE `id` = ? LIMIT 1;", []any{v.ID}
}
func (v Version) IDValue() any {
	return v.ID
}
func (v Version) ColumnID() sequel.ColumnClause[uuid.UUID] {
	return sequel.ValueColumn("id", v.ID)
}
