// Code generated by sqlgen. DO NOT EDIT.

package postgresdb

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"fmt"
	"iter"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
	"unsafe"

	"github.com/si3nloong/sqlgen/sequel"
	"github.com/si3nloong/sqlgen/sequel/driver/postgres/pgutil"
	"github.com/si3nloong/sqlgen/sequel/strpool"
)

func InsertOne[T sequel.ColumnValuer, Ptr interface {
	sequel.ColumnValuer
	sequel.PtrScanner[T]
}](ctx context.Context, db sequel.DB, model Ptr) error {
	switch v := any(model).(type) {
	case sequel.SingleInserter:
		query, args := v.InsertOneStmt()
		return db.QueryRowContext(ctx, query, args...).Scan(model.Addrs()...)
	case sequel.Inserter:
		stmt := strpool.AcquireString()
		stmt.WriteString("INSERT INTO ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(v.SQLInsertColumns())
		stmt.WriteString(" VALUES ")
		stmt.WriteString(v.SQLInsertPlaceholders(0))
		stmt.WriteString(" RETURNING ")
		stmt.WriteString(strings.Join(TableColumns(model), ","))
		stmt.WriteString(";")
		row := db.QueryRowContext(ctx, stmt.String(), v.SQLInsertValues()...)
		strpool.ReleaseString(stmt) // Cleanup
		return row.Scan(model.Addrs()...)
	default:
		columns, args := TableColumns(model), model.Values()
		columnSQL := strings.Join(columns, ",")
		stmt := strpool.AcquireString()
		stmt.WriteString("INSERT INTO ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" (")
		stmt.WriteString(columnSQL)
		stmt.WriteString(") VALUES ($1")
		noOfArgs := len(args)
		for i := 1; i < noOfArgs; i++ {
			stmt.WriteString(",")
			stmt.WriteString(wrapVar(i + 1))
		}
		stmt.WriteString(") RETURNING ")
		stmt.WriteString(columnSQL)
		stmt.WriteString(";")
		row := db.QueryRowContext(ctx, stmt.String(), args...)
		strpool.ReleaseString(stmt) // Cleanup
		args = nil                  // Cleanup
		return row.Scan(model.Addrs()...)
	}
}

// Insert is a helper function to insert multiple records.
func Insert[T sequel.ColumnValuer, Ptr sequel.PtrScanner[T]](ctx context.Context, db sequel.DB, data []T) (sql.Result, error) {
	noOfData := len(data)
	if noOfData == 0 {
		return new(sequel.EmptyResult), nil
	}

	model := data[0]
	columns := TableColumns(model)
	stmt := strpool.AcquireString()

	var (
		rows *sql.Rows
		err  error
	)
	switch v := any(model).(type) {
	case sequel.Inserter:
		noOfCols := len(columns)
		args := make([]any, 0, noOfCols*noOfData)
		stmt.WriteString("INSERT INTO ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" (")
		stmt.WriteString(v.SQLInsertColumns())
		stmt.WriteString(") VALUES ")
		stmt.WriteString(v.SQLInsertPlaceholders(0))
		args = append(args, data[0].Values()...)
		for i := 1; i < noOfData; i++ {
			stmt.WriteString(",")
			stmt.WriteString(v.SQLInsertPlaceholders(i))
			args = append(args, data[i].Values()...)
		}
		stmt.WriteString(" RETURNING ")
		stmt.WriteString(strings.Join(columns, ","))
		stmt.WriteString(";")
		rows, err = db.QueryContext(ctx, stmt.String(), args...)
		args = nil // Cleanup
	default:
		noOfCols := len(columns)
		args := make([]any, 0, noOfCols*noOfData)
		stmt.WriteString("INSERT INTO ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" (")
		stmt.WriteString(strings.Join(columns, ","))
		stmt.WriteString(") VALUES ($1")
		for i := 1; i < noOfCols; i++ {
			stmt.WriteString(",")
			stmt.WriteString(wrapVar(i + 1))
		}
		stmt.WriteString(")")
		args = append(args, data[0].Values()...)
		for i := 1; i < noOfData; i++ {
			stmt.WriteString(",(")
			stmt.WriteString(wrapVar(i*noOfCols + 1))
			for j := 1; j < noOfCols; j++ {
				stmt.WriteString(",")
				stmt.WriteString(wrapVar(i*noOfCols + j + 1))
			}
			stmt.WriteString(")")
			args = append(args, data[i].Values()...)
		}
		stmt.WriteString(" RETURNING ")
		stmt.WriteString(strings.Join(columns, ","))
		stmt.WriteString(";")
		rows, err = db.QueryContext(ctx, stmt.String(), args...)
		args = nil // Cleanup
	}
	strpool.ReleaseString(stmt) // Cleanup
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var count int64
	for rows.Next() {
		if err := rows.Scan(Ptr(&data[count]).Addrs()...); err != nil {
			return nil, err
		}
		count++
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return sequel.NewRowsAffectedResult(count), nil
}

type duplicateKeyer interface {
	DuplicateKeys() []string
}
type setOnUpsertOmitter interface {
	OnUpsertOmitColumns() []string
}
type upsertOpts struct {
	doNothing     bool
	omitFields    []string
	duplicateKeys []string
}
type UpsertOption func(*upsertOpts)

func WithDoNothing(doNothing bool) UpsertOption {
	return func(opt *upsertOpts) {
		opt.doNothing = doNothing
	}
}

func WithOmitFields(fields ...string) UpsertOption {
	return func(opt *upsertOpts) {
		opt.omitFields = fields
	}
}

func WithDuplicateKeys(keys ...string) UpsertOption {
	return func(opt *upsertOpts) {
		opt.duplicateKeys = keys
	}
}

func UpsertOne[T sequel.KeyValuer, Ptr interface {
	sequel.KeyValueScanner[T]
	sequel.Inserter
}](ctx context.Context, db sequel.DB, model Ptr, opts ...UpsertOption) error {
	var opt upsertOpts
	for i := range opts {
		opts[i](&opt)
	}

	var (
		stmt     = strpool.AcquireString()
		columns  = model.Columns()
		noOfCols = len(columns)
		values   = model.Values()
	)
	defer strpool.ReleaseString(stmt)

	switch v := any(model).(type) {
	case sequel.AutoIncrKeyer:
		pkName, idx, _ := v.PK()
		opt.omitFields = append(opt.omitFields, pkName)
		columns = append(columns[:idx], columns[idx+1:]...)
		values = append(values[:idx], values[idx+1:]...)
		// Don't include auto increment primary key on INSERT
		stmt.WriteString("INSERT INTO ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" (")
		stmt.WriteString(strings.Join(columns, ","))
		stmt.WriteString(") VALUES ")
	case sequel.PrimaryKeyer:
		pkName, _, _ := v.PK()
		opt.omitFields = append(opt.omitFields, pkName)
		stmt.WriteString("INSERT INTO ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" (")
		stmt.WriteString(strings.Join(columns, ","))
		stmt.WriteString(") VALUES ")
	case sequel.CompositeKeyer:
		keyNames, _, _ := v.CompositeKey()
		opt.omitFields = append(opt.omitFields, keyNames...)
		stmt.WriteString("INSERT INTO ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" (")
		stmt.WriteString(strings.Join(columns, ","))
		stmt.WriteString(") VALUES ")
	default:
		panic("unreachable")
	}
	stmt.WriteString(model.SQLInsertPlaceholders(0))
	if len(opt.duplicateKeys) > 0 {
		stmt.WriteString(" ON CONFLICT(")
		stmt.WriteString(strings.Join(opt.duplicateKeys, ","))
		stmt.WriteString(")")
	} else {
		switch vi := any(model).(type) {
		case duplicateKeyer:
			keys := vi.DuplicateKeys()
			opt.omitFields = append(opt.omitFields, keys...)
			stmt.WriteString(" ON CONFLICT(")
			stmt.WriteString(strings.Join(keys, ","))
			stmt.WriteString(")")
		case sequel.PrimaryKeyer:
			pkName, _, _ := vi.PK()
			stmt.WriteString(" ON CONFLICT(")
			stmt.WriteString(pkName)
			stmt.WriteString(")")
		case sequel.CompositeKeyer:
			names, _, _ := vi.CompositeKey()
			stmt.WriteString(" ON CONFLICT(")
			stmt.WriteString(strings.Join(names, ","))
			stmt.WriteString(")")
		default:
			panic("unreachable")
		}
	}
	if opt.doNothing {
		stmt.WriteString(" DO NOTHING")
	} else {
		stmt.WriteString(" DO UPDATE SET ")
		omitDict := make(map[string]struct{})
		noOfCols = len(columns)
		if omitter, ok := any(model).(setOnUpsertOmitter); ok {
			opt.omitFields = append(opt.omitFields, omitter.OnUpsertOmitColumns()...)
		}
		for i := range opt.omitFields {
			omitDict[opt.omitFields[i]] = struct{}{}
		}
		first := true
		for i := 0; i < noOfCols; i++ {
			if _, ok := omitDict[columns[i]]; ok {
				continue
			}
			if first {
				stmt.WriteString(columns[i] + " = EXCLUDED." + columns[i])
			} else {
				stmt.WriteString("," + columns[i] + " = EXCLUDED." + columns[i])
			}
			first = false
		}
		clear(omitDict)
	}
	stmt.WriteString(" RETURNING ")
	stmt.WriteString(strings.Join(TableColumns(model), ","))
	stmt.WriteString(";")
	return db.QueryRowContext(ctx, stmt.String(), values...).Scan(model.Addrs()...)
}

// Upsert is a helper function to upsert multiple records.
func Upsert[T interface {
	sequel.Keyer
	sequel.Inserter
}, Ptr sequel.PtrScanner[T]](ctx context.Context, db sequel.DB, data []T, opts ...UpsertOption) (sql.Result, error) {
	noOfData := len(data)
	if noOfData == 0 {
		return new(sequel.EmptyResult), nil
	}

	var (
		model    = data[0]
		columns  = model.Columns()
		noOfCols = len(columns)
		args     = make([]any, 0, noOfCols*noOfData)
		opt      upsertOpts
	)

	for i := range opts {
		opts[i](&opt)
	}

	var stmt = strpool.AcquireString()
	switch v := any(model).(type) {
	case sequel.AutoIncrKeyer:
		pkName, idx, _ := v.PK()
		opt.omitFields = append(opt.omitFields, pkName)
		columns = append(columns[:idx], columns[idx+1:]...)
		// Don't include auto increment primary key on INSERT
		stmt.WriteString("INSERT INTO ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" (")
		stmt.WriteString(model.SQLInsertColumns())
		stmt.WriteString(") VALUES ")
		stmt.WriteString(model.SQLInsertPlaceholders(0))
		values := data[0].Values()
		values = append(values[:idx], values[idx+1:]...)
		args = append(args, values...)
		for i := 1; i < noOfData; i++ {
			stmt.WriteString(",")
			stmt.WriteString(model.SQLInsertPlaceholders(i))
			values := data[i].Values()
			values = append(values[:idx], values[idx+1:]...)
			args = append(args, values...)
		}
	case sequel.PrimaryKeyer:
		pkName, _, _ := v.PK()
		opt.omitFields = append(opt.omitFields, pkName)
		stmt.WriteString("INSERT INTO ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" (")
		stmt.WriteString(model.SQLInsertColumns())
		stmt.WriteString(") VALUES ")
		stmt.WriteString(model.SQLInsertPlaceholders(0))
		args = append(args, data[0].Values()...)
		for i := 1; i < noOfData; i++ {
			stmt.WriteString(",")
			stmt.WriteString(model.SQLInsertPlaceholders(i))
			args = append(args, data[i].Values()...)
		}
	case sequel.CompositeKeyer:
		keyNames, _, _ := v.CompositeKey()
		opt.omitFields = append(opt.omitFields, keyNames...)
		stmt.WriteString("INSERT INTO ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" (")
		stmt.WriteString(model.SQLInsertColumns())
		stmt.WriteString(") VALUES ")
		stmt.WriteString(model.SQLInsertPlaceholders(0))
		args = append(args, data[0].Values()...)
		for i := 1; i < noOfData; i++ {
			stmt.WriteString(",")
			stmt.WriteString(model.SQLInsertPlaceholders(i))
			args = append(args, data[i].Values()...)
		}
	default:
		panic("unreachable")
	}
	if len(opt.duplicateKeys) > 0 {
		stmt.WriteString(" ON CONFLICT(" + strings.Join(opt.duplicateKeys, ",") + ")")
	} else {
		switch vi := any(model).(type) {
		case duplicateKeyer:
			keys := vi.DuplicateKeys()
			opt.omitFields = append(opt.omitFields, keys...)
			stmt.WriteString(" ON CONFLICT(")
			stmt.WriteString(strings.Join(keys, ","))
			stmt.WriteString(")")
		case sequel.PrimaryKeyer:
			pkName, _, _ := vi.PK()
			stmt.WriteString(" ON CONFLICT(")
			stmt.WriteString(pkName)
			stmt.WriteString(")")
		case sequel.CompositeKeyer:
			names, _, _ := vi.CompositeKey()
			// // Exclude primary key, don't update it
			// for i := len(idxs) - 1; i >= 0; i-- {
			// 	columns = append(columns[:idxs[i]], columns[idxs[i]+1:]...)
			// }
			stmt.WriteString(" ON CONFLICT(")
			stmt.WriteString(strings.Join(names, ","))
			stmt.WriteString(")")
		default:
			panic("unreachable")
		}
	}
	if opt.doNothing {
		stmt.WriteString(" DO NOTHING")
	} else {
		stmt.WriteString(" DO UPDATE SET ")
		omitDict := make(map[string]struct{})
		if omitter, ok := any(model).(setOnUpsertOmitter); ok {
			opt.omitFields = append(opt.omitFields, omitter.OnUpsertOmitColumns()...)
		}
		columns = model.Columns()
		for i := range opt.omitFields {
			omitDict[opt.omitFields[i]] = struct{}{}
		}
		first := true
		for i := 0; i < noOfCols; i++ {
			if _, ok := omitDict[columns[i]]; ok {
				continue
			}
			if first {
				stmt.WriteString(columns[i])
				stmt.WriteString(" = EXCLUDED.")
				stmt.WriteString(columns[i])
			} else {
				stmt.WriteString(",")
				stmt.WriteString(columns[i])
				stmt.WriteString(" = EXCLUDED.")
				stmt.WriteString(columns[i])
			}
			first = false
		}
		clear(omitDict)
	}
	stmt.WriteString(" RETURNING ")
	stmt.WriteString(strings.Join(TableColumns(model), ","))
	stmt.WriteString(";")
	rows, err := db.QueryContext(ctx, stmt.String(), args...)
	strpool.ReleaseString(stmt) // Deallocate statement
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var count int64
	for rows.Next() {
		if err := rows.Scan(Ptr(&data[count]).Addrs()...); err != nil {
			return nil, err
		}
		count++
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return sequel.NewRowsAffectedResult(count), nil
}

// FindByPK is to find single record using primary key.
func FindByPK[T sequel.KeyScanner, Ptr sequel.KeyPtrScanner[T]](ctx context.Context, db sequel.DB, model Ptr) error {
	switch v := any(model).(type) {
	case sequel.KeyFinder:
		query, args := v.FindOneByPKStmt()
		return db.QueryRowContext(ctx, query, args...).Scan(model.Addrs()...)
	case sequel.PrimaryKeyer:
		pkName, _, pk := v.PK()
		stmt := strpool.AcquireString()
		stmt.WriteString("SELECT ")
		stmt.WriteString(strings.Join(TableColumns(model), ","))
		stmt.WriteString(" FROM ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" WHERE ")
		stmt.WriteString(pkName)
		stmt.WriteString(" = $1 LIMIT 1;")
		row := db.QueryRowContext(ctx, stmt.String(), pk)
		strpool.ReleaseString(stmt)
		return row.Scan(model.Addrs()...)
	case sequel.CompositeKeyer:
		keyNames, _, keys := v.CompositeKey()
		stmt := strpool.AcquireString()
		stmt.WriteString("SELECT ")
		stmt.WriteString(strings.Join(TableColumns(model), ","))
		stmt.WriteString(" FROM ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" WHERE (")
		stmt.WriteString(strings.Join(keyNames, ","))
		stmt.WriteString(") = ($1")
		noOfKeys := len(keyNames)
		for i := 1; i < noOfKeys; i++ {
			stmt.WriteString(",")
			stmt.WriteString(wrapVar(i + 1))
		}
		stmt.WriteString(") LIMIT 1;")
		row := db.QueryRowContext(ctx, stmt.String(), keys...)
		strpool.ReleaseString(stmt)
		return row.Scan(model.Addrs()...)
	default:
		panic("unreachable")
	}
}

// UpdateByPK is to update single record using primary key.
func UpdateByPK[T sequel.KeyValuer](ctx context.Context, db sequel.DB, model T) (sql.Result, error) {
	switch v := any(model).(type) {
	case sequel.KeyUpdater:
		query, args := v.UpdateOneByPKStmt()
		return db.ExecContext(ctx, query, args...)
	case sequel.PrimaryKeyer:
		pkName, pkIdx, pk := v.PK()
		columns := model.Columns()
		columns = append(columns[:pkIdx], columns[pkIdx+1:]...)
		values := model.Values()
		values = append(values[:pkIdx], append(values[pkIdx+1:], pk)...)
		stmt := strpool.AcquireString()
		stmt.WriteString("UPDATE ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" SET ")
		stmt.WriteString(columns[0])
		stmt.WriteString(" = ")
		stmt.WriteString(wrapVar(1))
		noOfColumn := len(columns)
		for i := 1; i < noOfColumn; i++ {
			stmt.WriteString(",")
			stmt.WriteString(columns[i])
			stmt.WriteString(" = ")
			stmt.WriteString(wrapVar(i + 1))
		}
		stmt.WriteString(" WHERE ")
		stmt.WriteString(pkName)
		stmt.WriteString(" = ")
		stmt.WriteString(wrapVar(noOfColumn + 2))
		stmt.WriteString(";")
		result, err := db.ExecContext(ctx, stmt.String(), append(values, pk)...)
		strpool.ReleaseString(stmt)
		return result, err
	case sequel.CompositeKeyer:
		columns := model.Columns()
		keyNames, keyIdxs, keys := v.CompositeKey()
		values := model.Values()
		sort.Ints(keyIdxs)
		for i := len(keyIdxs) - 1; i >= 0; i-- {
			columns = append(columns[:keyIdxs[i]], columns[keyIdxs[i]+1:]...)
			values = append(values[:keyIdxs[i]], values[keyIdxs[i]+1:]...)
		}
		noOfColumn := len(columns)
		args := make([]any, 0, noOfColumn+len(keys))
		stmt := strpool.AcquireString()
		defer strpool.ReleaseString(stmt)
		stmt.WriteString("UPDATE ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" SET ")
		stmt.WriteString(columns[0])
		stmt.WriteString(" = ")
		stmt.WriteString(wrapVar(1))
		for i := 1; i < noOfColumn; i++ {
			stmt.WriteString(",")
			stmt.WriteString(columns[i])
			stmt.WriteString(" = ")
			stmt.WriteString(wrapVar(i + 1))
		}
		stmt.WriteString(" WHERE (")
		stmt.WriteString(strings.Join(keyNames, ","))
		stmt.WriteString(") = (")
		stmt.WriteString(wrapVar(noOfColumn + 1))
		noOfKey := len(keyNames)
		for i := 1; i < noOfKey; i++ {
			stmt.WriteString(",")
			stmt.WriteString(columns[i])
			stmt.WriteString(" = ")
			stmt.WriteString(wrapVar(noOfColumn + i + 1))
		}
		stmt.WriteString(");")
		args = append(args, values...)
		return db.ExecContext(ctx, stmt.String(), append(args, keys...)...)
	default:
		panic("unreachable")
	}
}

// DeleteByPK is to update single record using primary key.
func DeleteByPK[T sequel.KeyValuer](ctx context.Context, db sequel.DB, model T) (sql.Result, error) {
	switch v := any(model).(type) {
	case sequel.KeyDeleter:
		query, args := v.DeleteOneByPKStmt()
		return db.ExecContext(ctx, query, args...)
	case sequel.PrimaryKeyer:
		pkName, _, pk := v.PK()
		stmt := strpool.AcquireString()
		stmt.WriteString("DELETE FROM ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" WHERE ")
		stmt.WriteString(pkName)
		stmt.WriteString(" = $1;")
		result, err := db.ExecContext(ctx, stmt.String(), pk)
		strpool.ReleaseString(stmt)
		return result, err
	case sequel.CompositeKeyer:
		keyNames, _, keys := v.CompositeKey()
		stmt := strpool.AcquireString()
		stmt.WriteString("DELETE FROM ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" WHERE (")
		stmt.WriteString(strings.Join(keyNames, ","))
		stmt.WriteString(") = ($1")
		noOfKey := len(keyNames)
		for i := 1; i < noOfKey; i++ {
			stmt.WriteString(",")
			stmt.WriteString(wrapVar(i + 1))
		}
		stmt.WriteString(");")
		result, err := db.ExecContext(ctx, stmt.String(), keys...)
		strpool.ReleaseString(stmt) // Clean up
		keys = nil                  // Clean up
		return result, err
	default:
		panic("unreachable")
	}
}

type LockMode string

func (l LockMode) LockMode() string {
	return (string)(l)
}

const (
	LockForUpdate      LockMode = "FOR UPDATE"
	LockForNoKeyUpdate LockMode = "FOR NO KEY UPDATE"
	LockForShare       LockMode = "FOR SHARE"
	LockForKeyShare    LockMode = "FOR KEY SHARE"
)

func LockByPK[T sequel.KeyScanner, Ptr sequel.KeyPtrScanner[T]](ctx context.Context, tx *sql.Tx, model Ptr, locker sequel.RowLevelLocker) error {
	stmt := strpool.AcquireString()
	switch v := any(model).(type) {
	case sequel.PrimaryKeyer:
		pkName, _, pk := v.PK()
		stmt.WriteString("SELECT ")
		stmt.WriteString(strings.Join(TableColumns(model), ","))
		stmt.WriteString(" FROM ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" WHERE ")
		stmt.WriteString(pkName)
		stmt.WriteString(" = $1 LIMIT 1 ")
		stmt.WriteString(locker.LockMode())
		stmt.WriteString(";")
		row := tx.QueryRowContext(ctx, stmt.String(), pk)
		strpool.ReleaseString(stmt)
		return row.Scan(model.Addrs()...)
	case sequel.CompositeKeyer:
		keyNames, _, keys := v.CompositeKey()
		stmt.WriteString("SELECT ")
		stmt.WriteString(strings.Join(TableColumns(model), ","))
		stmt.WriteString(" FROM ")
		stmt.WriteString(DbTable(model))
		stmt.WriteString(" WHERE ")
		stmt.WriteString("(")
		stmt.WriteString(strings.Join(keyNames, ","))
		stmt.WriteString(") = ($1")
		noOfKey := len(keyNames)
		for i := 1; i < noOfKey; i++ {
			stmt.WriteString(",")
			stmt.WriteString(wrapVar(i + 1))
		}
		stmt.WriteString(") LIMIT 1 ")
		stmt.WriteString(locker.LockMode())
		stmt.WriteString(";")
		row := tx.QueryRowContext(ctx, stmt.String(), keys...)
		strpool.ReleaseString(stmt)
		return row.Scan(model.Addrs()...)
	default:
		panic("unreachable")
	}
}

type PaginateStmt struct {
	Select    []string
	FromTable string
	Where     sequel.WhereClause
	OrderBy   []sequel.OrderByClause
	Limit     uint16
}

func Paginate[T sequel.KeyValuer, Ptr sequel.KeyValueScanner[T]](stmt PaginateStmt) *Pager[T, Ptr] {
	// Set default limit
	if stmt.Limit == 0 {
		stmt.Limit = 100
	}
	return &Pager[T, Ptr]{
		stmt: &stmt,
	}
}

type Pager[T sequel.KeyValuer, Ptr sequel.KeyValueScanner[T]] struct {
	stmt *PaginateStmt
}

func (r *Pager[T, Ptr]) Prev(ctx context.Context, db sequel.DB, cursor ...T) iter.Seq2[[]T, error] {
	return func(yield func([]T, error) bool) {
		var (
			v         T
			hasCursor bool
			maxLimit  = r.stmt.Limit
			rows      *sql.Rows
			err       error
			noOfData  int
			data      = make([]T, 0, r.stmt.Limit+1) // Add one to limit to find prev cursor
		)
		if len(cursor) > 0 {
			v = cursor[0]
			hasCursor = true
		}

		stmt := AcquireStmt()
		defer ReleaseStmt(stmt)

		for {
			if hasCursor {
				if err = FindByPK(ctx, db, Ptr(&v)); err != nil {
					yield(nil, err)
					return
				}
			}

			stmt.WriteString("SELECT ")
			stmt.WriteString(strings.Join(TableColumns(v), ","))
			stmt.WriteString(" FROM ")
			stmt.WriteString(DbTable(v))

			if r.stmt.Where != nil || len(r.stmt.OrderBy) > 0 || hasCursor {
				stmt.WriteString(" WHERE ")
				if r.stmt.Where != nil {
					r.stmt.Where(stmt)
				}
				if n := len(r.stmt.OrderBy); n > 0 {
					colDict := make(map[string]int)
					columns := v.Columns()
					values := v.Values()
					for i := range columns {
						colDict[columns[i]] = i
					}

					buf := strpool.AcquireString()
					for i := 0; i < n; i++ {
						orderedColumn := r.stmt.OrderBy[i]
						columnName := orderedColumn.ColumnName()
						value := values[colDict[columnName]]
						if orderedColumn.Asc() {
							// If ascending
							stmt.WriteString(columnName)
							stmt.WriteString(" <= ")
							stmt.WriteString(stmt.Var(value))
							stmt.WriteString(" AND ")
							buf.WriteString(columnName)
							buf.WriteString(" < ")
							buf.WriteString(stmt.Var(value))
							buf.WriteString(" OR ")
						} else {
							// If descending
							stmt.WriteString(columnName)
							stmt.WriteString(" >= ")
							stmt.WriteString(stmt.Var(value))
							stmt.WriteString(" AND ")
							buf.WriteString(columnName)
							buf.WriteString(" > ")
							buf.WriteString(stmt.Var(value))
							buf.WriteString(" OR ")
						}
					}
					clear(colDict)
					stmt.WriteString("(")
					stmt.WriteString(buf.String())
					strpool.ReleaseString(buf)
				}

				if hasCursor {
					// Check the primary key and compare value
					switch vi := any(v).(type) {
					case sequel.CompositeKeyer:
						pkNames, _, vals := vi.CompositeKey()
						stmt.WriteString("((")
						stmt.WriteString(strings.Join(pkNames, ","))
						stmt.WriteString(") <= ")
						stmt.WriteString(stmt.Vars(vals))
						stmt.WriteString(")")
					case sequel.PrimaryKeyer:
						pkName, _, val := vi.PK()
						stmt.WriteString("(")
						stmt.WriteString(pkName)
						stmt.WriteString(" <= ")
						stmt.WriteString(stmt.Var(val))
						stmt.WriteString(")")
					default:
						panic("unreachable")
					}
				}
			}

			stmt.WriteString(" ORDER BY ")
			if len(r.stmt.OrderBy) > 0 {
				for i := range r.stmt.OrderBy {
					if r.stmt.OrderBy[i].Asc() {
						stmt.WriteString(r.stmt.OrderBy[i].ColumnName())
						stmt.WriteString(" ASC,")
					} else {
						stmt.WriteString(r.stmt.OrderBy[i].ColumnName())
						stmt.WriteString(" DESC,")
					}
				}
				var (
					suffix  = " DESC"
					lastCol = r.stmt.OrderBy[len(r.stmt.OrderBy)-1]
				)
				if lastCol.Asc() {
					suffix = " ASC"
				}
				switch vi := any(v).(type) {
				case sequel.CompositeKeyer:
					pkNames, _, _ := vi.CompositeKey()
					stmt.WriteString("(")
					stmt.WriteString(strings.Join(pkNames, ","))
					stmt.WriteString(")")
					stmt.WriteString(suffix)
				case sequel.PrimaryKeyer:
					pkName, _, _ := vi.PK()
					stmt.WriteString(pkName)
					stmt.WriteString(suffix)
				default:
					panic("unreachable")
				}
			} else {
				// If there is no order by clause,
				// descending is the default order
				switch vi := any(v).(type) {
				case sequel.CompositeKeyer:
					pkNames, _, _ := vi.CompositeKey()
					stmt.WriteString("(")
					stmt.WriteString(strings.Join(pkNames, ","))
					stmt.WriteString(") DESC")
				case sequel.PrimaryKeyer:
					pkName, _, _ := vi.PK()
					stmt.WriteString(pkName)
					stmt.WriteString(" DESC")
				default:
					panic("unreachable")
				}
			}
			// Add one to limit to find next cursor
			stmt.WriteString(" LIMIT ")
			stmt.WriteString(strconv.Itoa((int)(r.stmt.Limit + 1)))
			stmt.WriteString(";")

			rows, err = db.QueryContext(ctx, stmt.Query(), stmt.Args()...)
			stmt.Reset()
			if err != nil {
				yield(nil, err)
				return
			}

			for rows.Next() {
				var v T
				if err := rows.Scan(Ptr(&v).Addrs()...); err != nil {
					rows.Close()
					yield(nil, err)
					return
				}
				data = append(data, v)
			}
			if err = rows.Close(); err != nil {
				yield(nil, err)
				return
			}
			if err = rows.Err(); err != nil {
				yield(nil, err)
				return
			}

			noOfData = len(data)
			if uint16(noOfData) <= maxLimit {
				yield(data, nil)
				return
			}

			if !yield(data[:noOfData-1], nil) {
				return
			}

			v = data[noOfData-1] // Set previous cursor
			data = data[:0]      // Reset result
			hasCursor = true
		}
	}
}

func (r *Pager[T, Ptr]) Next(ctx context.Context, db sequel.DB, cursor ...T) iter.Seq2[[]T, error] {
	return func(yield func([]T, error) bool) {
		var (
			v         T
			hasCursor bool
			maxLimit  = r.stmt.Limit
			rows      *sql.Rows
			err       error
			noOfData  int
			data      = make([]T, 0, r.stmt.Limit+1) // Add one to limit to find next cursor
		)
		if len(cursor) > 0 {
			v = cursor[0]
			hasCursor = true
		}

		stmt := AcquireStmt()
		defer ReleaseStmt(stmt)

		for {
			if hasCursor {
				if err = FindByPK(ctx, db, Ptr(&v)); err != nil {
					yield(nil, err)
					return
				}
			}

			stmt.WriteString("SELECT ")
			stmt.WriteString(strings.Join(TableColumns(v), ","))
			stmt.WriteString(" FROM ")
			stmt.WriteString(DbTable(v))
			if r.stmt.Where != nil || len(r.stmt.OrderBy) > 0 || hasCursor {
				stmt.WriteString(" WHERE ")
				if r.stmt.Where != nil {
					r.stmt.Where(stmt)
				}

				if len(r.stmt.OrderBy) > 0 {
					colDict := make(map[string]int)
					columns := v.Columns()
					values := v.Values()
					for i := range columns {
						colDict[columns[i]] = i
					}

					for i, orderBy := range r.stmt.OrderBy {
						colName := orderBy.ColumnName()
						val := values[colDict[colName]]
						if i > 0 {
							stmt.WriteString(" AND ")
						}
						if orderBy.Asc() {
							// If ascending
							stmt.WriteString(colName)
							stmt.WriteString(" >= ")
							stmt.WriteString(stmt.Var(val))
						} else {
							// If descending
							stmt.WriteString(colName)
							stmt.WriteString(" <= ")
							stmt.WriteString(stmt.Var(val))
						}
					}
					stmt.WriteString(" AND (")
					for i, orderBy := range r.stmt.OrderBy {
						colName := orderBy.ColumnName()
						val := values[colDict[colName]]
						if i > 0 {
							stmt.WriteString(" OR ")
						}
						if orderBy.Asc() {
							// If ascending
							stmt.WriteString(colName)
							stmt.WriteString(" > ")
							stmt.WriteString(stmt.Var(val))
						} else {
							// If descending
							stmt.WriteString(colName)
							stmt.WriteString(" < ")
							stmt.WriteString(stmt.Var(val))
						}
					}
					clear(colDict)
					stmt.WriteString(" OR ")
				}

				if hasCursor {
					// Check the primary key and compare value
					switch vi := any(v).(type) {
					case sequel.CompositeKeyer:
						pkNames, _, vals := vi.CompositeKey()
						stmt.WriteString("((")
						stmt.WriteString(strings.Join(pkNames, ","))
						stmt.WriteString(") >= ")
						stmt.WriteString(stmt.Vars(vals))
						stmt.WriteString(")")
					case sequel.PrimaryKeyer:
						pkName, _, val := vi.PK()
						stmt.WriteString("(")
						stmt.WriteString(pkName)
						stmt.WriteString(" >= ")
						stmt.WriteString(stmt.Var(val))
						stmt.WriteString(")")
					default:
						panic("unreachable")
					}
				}
			}

			stmt.WriteString(" ORDER BY ")
			if len(r.stmt.OrderBy) > 0 {
				for i := range r.stmt.OrderBy {
					if r.stmt.OrderBy[i].Asc() {
						stmt.WriteString(r.stmt.OrderBy[i].ColumnName())
						stmt.WriteString(" ASC,")
					} else {
						stmt.WriteString(r.stmt.OrderBy[i].ColumnName())
						stmt.WriteString(" DESC,")
					}
				}
				var (
					suffix  = " ASC"
					lastCol = r.stmt.OrderBy[len(r.stmt.OrderBy)-1]
				)
				if !lastCol.Asc() {
					suffix = " DESC"
				}
				switch vi := any(v).(type) {
				case sequel.CompositeKeyer:
					pkNames, _, _ := vi.CompositeKey()
					stmt.WriteString("(")
					stmt.WriteString(strings.Join(pkNames, ","))
					stmt.WriteString(")")
					stmt.WriteString(suffix)
				case sequel.PrimaryKeyer:
					pkName, _, _ := vi.PK()
					stmt.WriteString(pkName)
					stmt.WriteString(suffix)
				default:
					panic("unreachable")
				}
			} else {
				// If there is no order by clause,
				// ascending is the default order
				switch vi := any(v).(type) {
				case sequel.CompositeKeyer:
					pkNames, _, _ := vi.CompositeKey()
					stmt.WriteString("(")
					stmt.WriteString(strings.Join(pkNames, ","))
					stmt.WriteString(") ASC")
				case sequel.PrimaryKeyer:
					pkName, _, _ := vi.PK()
					stmt.WriteString(pkName)
					stmt.WriteString(" ASC")
				default:
					panic("unreachable")
				}
			}
			stmt.WriteString(" LIMIT ")
			stmt.WriteString(strconv.Itoa((int)(r.stmt.Limit + 1)))
			stmt.WriteString(";")

			rows, err = db.QueryContext(ctx, stmt.Query(), stmt.Args()...)
			stmt.Reset()
			if err != nil {
				yield(nil, err)
				return
			}

			for rows.Next() {
				var v T
				if err = rows.Scan(Ptr(&v).Addrs()...); err != nil {
					rows.Close()
					yield(nil, err)
					return
				}
				data = append(data, v)
			}
			if err = rows.Close(); err != nil {
				yield(nil, err)
				return
			}
			if err = rows.Err(); err != nil {
				yield(nil, err)
				return
			}

			noOfData = len(data)
			if uint16(noOfData) <= maxLimit {
				yield(data, nil)
				return
			}

			if !yield(data[:noOfData-1], nil) {
				return
			}

			v = data[noOfData-1] // Set next cursor
			data = data[:0]      // Reset result
			hasCursor = true
		}
	}
}

type SelectStmt struct {
	Select    []string
	FromTable string
	Where     sequel.WhereClause
	OrderBy   []sequel.OrderByClause
	GroupBy   []string
	Offset    uint64
	Limit     uint16
}

func QueryStmt[T any, Ptr sequel.PtrScanner[T]](ctx context.Context, db sequel.DB, stmtFunc func(T) SelectStmt) ([]T, error) {
	var v T
	selectStmt := stmtFunc(v)
	stmt := AcquireStmt()
	stmt.WriteString("SELECT ")
	if len(selectStmt.Select) > 0 {
		stmt.WriteString(strings.Join(selectStmt.Select, ","))
	} else {
		switch vj := any(v).(type) {
		case sequel.Columner:
			stmt.WriteString(strings.Join(TableColumns(vj), ","))
		default:
			stmt.WriteString("*")
		}
	}
	if selectStmt.FromTable != "" {
		stmt.WriteString(" FROM ")
		stmt.WriteString(dbName(v))
		stmt.WriteString(selectStmt.FromTable)
	} else {
		switch vj := any(v).(type) {
		case sequel.Tabler:
			stmt.WriteString(" FROM ")
			stmt.WriteString(DbTable(vj))
		default:
			ReleaseStmt(stmt)
			return nil, fmt.Errorf("missing table name for model %T", v)
		}
	}
	if selectStmt.Where != nil {
		stmt.WriteString(" WHERE ")
		selectStmt.Where(stmt)
	}
	if n := len(selectStmt.GroupBy); n > 0 {
		stmt.WriteString(" GROUP BY ")
		stmt.WriteString(selectStmt.GroupBy[0])
		for i := 1; i < n; i++ {
			stmt.WriteString(",")
			stmt.WriteString(selectStmt.GroupBy[i])
		}
	}
	if n := len(selectStmt.OrderBy); n > 0 {
		if selectStmt.OrderBy[0].Asc() {
			stmt.WriteString(" ORDER BY ")
			stmt.WriteString(selectStmt.OrderBy[0].ColumnName())
		} else {
			stmt.WriteString(" ORDER BY ")
			stmt.WriteString(selectStmt.OrderBy[0].ColumnName())
			stmt.WriteString(" DESC")
		}
		for i := 1; i < n; i++ {
			if selectStmt.OrderBy[i].Asc() {
				stmt.WriteString(",")
				stmt.WriteString(selectStmt.OrderBy[i].ColumnName())
			} else {
				stmt.WriteString(",")
				stmt.WriteString(selectStmt.OrderBy[i].ColumnName())
				stmt.WriteString(" DESC")
			}
		}
	}
	if selectStmt.Limit > 0 {
		stmt.WriteString(" LIMIT ")
		stmt.WriteString(strconv.Itoa((int)(selectStmt.Limit)))
	}
	if selectStmt.Offset > 0 {
		stmt.WriteString(" OFFSET ")
		stmt.WriteString(strconv.FormatUint(selectStmt.Offset, 10))
	}
	stmt.WriteString(";")
	rows, err := db.QueryContext(ctx, stmt.Query(), stmt.Args()...)
	ReleaseStmt(stmt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var result []T
	for rows.Next() {
		var v T
		if err := rows.Scan(Ptr(&v).Addrs()...); err != nil {
			return nil, err
		}
		result = append(result, v)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return result, nil
}

type SelectOneStmt struct {
	Select    []string
	FromTable string
	Where     sequel.WhereClause
	OrderBy   []sequel.OrderByClause
	GroupBy   []string
}

func QueryOneStmt[T any, Ptr sequel.PtrScanner[T]](ctx context.Context, db sequel.DB, stmtFunc func(T) SelectOneStmt) (Ptr, error) {
	var v T
	selectOneStmt := stmtFunc(v)
	stmt := AcquireStmt()
	stmt.WriteString("SELECT ")
	if len(selectOneStmt.Select) > 0 {
		stmt.WriteString(strings.Join(selectOneStmt.Select, ","))
	} else {
		switch vj := any(v).(type) {
		case sequel.Columner:
			stmt.WriteString(strings.Join(TableColumns(vj), ","))
		default:
			stmt.WriteString("*")
		}
	}
	if selectOneStmt.FromTable != "" {
		stmt.WriteString(" FROM ")
		stmt.WriteString(dbName(v))
		stmt.WriteString(selectOneStmt.FromTable)
	} else {
		switch vj := any(v).(type) {
		case sequel.Tabler:
			stmt.WriteString(" FROM ")
			stmt.WriteString(DbTable(vj))
		default:
			return nil, fmt.Errorf("missing table name for model %T", v)
		}
	}
	if selectOneStmt.Where != nil {
		stmt.WriteString(" WHERE ")
		selectOneStmt.Where(stmt)
	}
	if n := len(selectOneStmt.GroupBy); n > 0 {
		stmt.WriteString(" GROUP BY ")
		stmt.WriteString(selectOneStmt.GroupBy[0])
		for i := 1; i < n; i++ {
			stmt.WriteString(",")
			stmt.WriteString(selectOneStmt.GroupBy[i])
		}
	}
	if n := len(selectOneStmt.OrderBy); n > 0 {
		if selectOneStmt.OrderBy[0].Asc() {
			stmt.WriteString(" ORDER BY ")
			stmt.WriteString(selectOneStmt.OrderBy[0].ColumnName())
		} else {
			stmt.WriteString(" ORDER BY ")
			stmt.WriteString(selectOneStmt.OrderBy[0].ColumnName())
			stmt.WriteString(" DESC")
		}
		for i := 1; i < n; i++ {
			if selectOneStmt.OrderBy[i].Asc() {
				stmt.WriteString(",")
				stmt.WriteString(selectOneStmt.OrderBy[i].ColumnName())
			} else {
				stmt.WriteString(",")
				stmt.WriteString(selectOneStmt.OrderBy[i].ColumnName())
				stmt.WriteString(" DESC")
			}
		}
	}
	stmt.WriteString(" LIMIT 1;")
	row := db.QueryRowContext(ctx, stmt.Query(), stmt.Args()...)
	ReleaseStmt(stmt)
	if err := row.Scan(Ptr(&v).Addrs()...); err != nil {
		return nil, err
	}
	return &v, nil
}

type UpdateStmt struct {
	Table   string
	Set     []sequel.SetClause
	Where   sequel.WhereClause
	OrderBy []sequel.OrderByClause
}

type DeleteStmt struct {
	FromTable string
	Where     sequel.WhereClause
	OrderBy   []sequel.OrderByClause
}

func ExecStmt[T any, Stmt interface {
	UpdateStmt | DeleteStmt
}](ctx context.Context, db sequel.DB, stmtFunc func(T) Stmt) (sql.Result, error) {
	var v T
	stmt := AcquireStmt()
	defer ReleaseStmt(stmt)

	switch vi := any(stmtFunc(v)).(type) {
	case UpdateStmt:
		if vt, ok := any(v).(sequel.Tabler); ok {
			stmt.WriteString("UPDATE ")
			stmt.WriteString(DbTable(vt))
		} else {
			stmt.WriteString("UPDATE ")
			stmt.WriteString(dbName(v))
			stmt.WriteString(vi.Table)
		}
		if len(vi.Set) > 0 {
			stmt.WriteString(" SET ")
			vi.Set[0](stmt)
			for i := 1; i < len(vi.Set); i++ {
				stmt.WriteString(",")
				vi.Set[i](stmt)
			}
		}
		if vi.Where != nil {
			stmt.WriteString(" WHERE ")
			vi.Where(stmt)
		}
		if n := len(vi.OrderBy); n > 0 {
			if vi.OrderBy[0].Asc() {
				stmt.WriteString(" ORDER BY ")
				stmt.WriteString(vi.OrderBy[0].ColumnName())
			} else {
				stmt.WriteString(" ORDER BY ")
				stmt.WriteString(vi.OrderBy[0].ColumnName())
				stmt.WriteString(" DESC")
			}
			for i := 1; i < n; i++ {
				if vi.OrderBy[i].Asc() {
					stmt.WriteString(",")
					stmt.WriteString(vi.OrderBy[i].ColumnName())
					stmt.WriteString(" ASC")
				} else {
					stmt.WriteString(",")
					stmt.WriteString(vi.OrderBy[i].ColumnName())
					stmt.WriteString(" DESC")
				}
			}
		}
	case DeleteStmt:
		if vt, ok := any(v).(sequel.Tabler); ok {
			stmt.WriteString("DELETE FROM ")
			stmt.WriteString(DbTable(vt))
		} else {
			stmt.WriteString("DELETE FROM ")
			stmt.WriteString(dbName(v))
			stmt.WriteString(vi.FromTable)
		}
		if vi.Where != nil {
			stmt.WriteString(" WHERE ")
			vi.Where(stmt)
		}
		if n := len(vi.OrderBy); n > 0 {
			if vi.OrderBy[0].Asc() {
				stmt.WriteString(" ORDER BY ")
				stmt.WriteString(vi.OrderBy[0].ColumnName())
			} else {
				stmt.WriteString(" ORDER BY ")
				stmt.WriteString(vi.OrderBy[0].ColumnName())
				stmt.WriteString(" DESC")
			}
			for i := 1; i < n; i++ {
				if vi.OrderBy[i].Asc() {
					stmt.WriteString(",")
					stmt.WriteString(vi.OrderBy[i].ColumnName())
				} else {
					stmt.WriteString(",")
					stmt.WriteString(vi.OrderBy[i].ColumnName())
					stmt.WriteString(" DESC")
				}
			}
		}
	}
	stmt.WriteString(";")
	return db.ExecContext(ctx, stmt.Query(), stmt.Args()...)
}

var (
	pool = sync.Pool{
		New: func() any {
			return new(SqlStmt)
		},
	}
)

func AcquireStmt() *SqlStmt {
	return pool.Get().(*SqlStmt)
}

func ReleaseStmt(stmt *SqlStmt) {
	if stmt != nil {
		stmt.Reset()
		pool.Put(stmt)
	}
}

type SqlStmt struct {
	blr  strings.Builder
	pos  int
	args []any
}

var (
	_ sequel.Stmt = (*SqlStmt)(nil)
)

func (s *SqlStmt) Var(value any) string {
	s.pos++
	s.args = append(s.args, value)
	return wrapVar(s.pos)
}

func (s *SqlStmt) Vars(values []any) string {
	noOfLen := len(values)
	s.args = append(s.args, values...)
	buf := new(strings.Builder)
	buf.WriteString("(")
	i := s.pos
	s.pos += noOfLen
	for ; i < s.pos; i++ {
		if i < s.pos-1 {
			buf.WriteString(wrapVar(i+1) + ",")
		} else {
			buf.WriteString(wrapVar(i + 1))
		}
	}
	buf.WriteString(")")
	return buf.String()
}

func (s *SqlStmt) Write(p []byte) (int, error) {
	return s.blr.Write(p)
}

func (s *SqlStmt) WriteString(v string) (int, error) {
	return s.blr.WriteString(v)
}

func (s *SqlStmt) Quote(v string) string {
	return pgutil.Quote(v)
}

func (s *SqlStmt) Query() string {
	return s.blr.String()
}

func (s SqlStmt) Args() []any {
	return s.args
}

func (s *SqlStmt) Format(f fmt.State, verb rune) {
	str := s.blr.String()
	switch verb {
	case 's':
		f.Write(unsafe.Slice(unsafe.StringData(str), len(str)))
		return
	case 'v':
		if !f.Flag('#') && !f.Flag('+') {
			f.Write(unsafe.Slice(unsafe.StringData(str), len(str)))
			return
		}
	}

	var (
		args = make([]any, len(s.args))
		idx  int
		i    = 1
	)

	copy(args, s.args)

	for {
		placeholder := wrapVar(i)
		idx = strings.Index(str, placeholder)
		if idx < 0 {
			f.Write(unsafe.Slice(unsafe.StringData(str), len(str)))
			break
		}

		f.Write([]byte(str[:idx]))
		v := strf(args[0])
		f.Write(unsafe.Slice(unsafe.StringData(v), len(v)))
		str = str[idx+len(placeholder):]
		args = args[1:]
		i++
	}
}

func (s *SqlStmt) Reset() {
	s.args = nil
	s.pos = 0
	s.blr.Reset()
}

func DbTable[T sequel.Tabler](model T) string {
	if v, ok := any(model).(sequel.Databaser); ok {
		return v.DatabaseName() + "." + model.TableName()
	}
	return model.TableName()
}

func TableColumns[T sequel.Columner](model T) []string {
	if v, ok := any(model).(sequel.SQLColumner); ok {
		return v.SQLColumns()
	}
	return model.Columns()
}

func dbName(model any) string {
	if v, ok := model.(sequel.Databaser); ok {
		return v.DatabaseName() + "."
	}
	return ""
}

func wrapVar(i int) string {
	return `$` + strconv.Itoa(i)
}

func strf(v any) string {
	switch vi := v.(type) {
	case nil:
		return "NULL"
	case string:
		return pgutil.Quote(vi)
	case []byte:
		return pgutil.Quote(unsafe.String(unsafe.SliceData(vi), len(vi)))
	case bool:
		return strconv.FormatBool(vi)
	case int64:
		return strconv.FormatInt(vi, 10)
	case float64:
		return strconv.FormatFloat(vi, 'f', 10, 64)
	case time.Time:
		return strconv.Quote(vi.Format(time.RFC3339))
	case sql.RawBytes:
		return unsafe.String(unsafe.SliceData(vi), len(vi))
	case driver.Valuer:
		val, _ := vi.Value()
		return strf(val)
	default:
		vt := reflect.ValueOf(v)
		switch vt.Kind() {
		case reflect.String:
			return pgutil.Quote(vt.String())
		case reflect.Bool:
			return strconv.FormatBool(vt.Bool())
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
			return strconv.FormatInt(vt.Int(), 10)
		case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
			return strconv.FormatUint(vt.Uint(), 10)
		case reflect.Float32, reflect.Float64:
			return strconv.FormatFloat(vt.Float(), 'f', 10, 64)
		default:
			panic("unreachable")
		}
	}
}
