// Code generated by sqlgen. DO NOT EDIT.

package aliasstruct

import (
	"cloud.google.com/go/civil"
	"github.com/si3nloong/sqlgen/sequel"
)

func (A) Columns() []string {
	return []string{"date", "time"} // 2
}
func (v A) Values() []any {
	return []any{
		v.Date, // 0 - date
		v.Time, // 1 - time
	}
}
func (v *A) Addrs() []any {
	return []any{
		&v.Date, // 0 - date
		&v.Time, // 1 - time
	}
}
func (A) SQLInsertPlaceholders(row int) string {
	return "(?,?)" // 2
}
func (v A) InsertOneStmt() (string, []any) {
	return "INSERT INTO " + v.TableName() + " (`date`,`time`) VALUES (?,?);", v.Values()
}
func (v A) DateValue() any {
	return v.Date
}
func (v A) TimeValue() any {
	return v.Time
}
func (v A) ColumnDate() sequel.ColumnClause[civil.Date] {
	return sequel.ValueColumn("date", v.Date)
}
func (v A) ColumnTime() sequel.ColumnClause[civil.Time] {
	return sequel.ValueColumn("time", v.Time)
}

func (C) TableName() string {
	return "c"
}
func (C) Columns() []string {
	return []string{"string", "valid"} // 2
}
func (v C) Values() []any {
	return []any{
		v.String, // 0 - string
		v.Valid,  // 1 - valid
	}
}
func (v *C) Addrs() []any {
	return []any{
		&v.String, // 0 - string
		&v.Valid,  // 1 - valid
	}
}
func (C) SQLInsertPlaceholders(row int) string {
	return "(?,?)" // 2
}
func (v C) InsertOneStmt() (string, []any) {
	return "INSERT INTO `c` (`string`,`valid`) VALUES (?,?);", v.Values()
}
func (v C) StringValue() any {
	return v.String
}
func (v C) ValidValue() any {
	return v.Valid
}
func (v C) ColumnString() sequel.ColumnClause[string] {
	return sequel.PrimitiveColumn("string", v.String)
}
func (v C) ColumnValid() sequel.ColumnClause[bool] {
	return sequel.PrimitiveColumn("valid", v.Valid)
}
