// Code generated by sqlgen, version 1.0.0. DO NOT EDIT.

package aliasproperty


func (AliasStruct) Columns() []string {
    return []string{"Name", "DateTime"}
}

func (m AliasStruct) Values() []any {
	return []any{aliasStr(m.Name), t.Time(m.DateTime)}
}

func (m *AliasStruct) Addrs() []any {
	return []any{types.String(&m.Name), types.String(&m.DateTime)}
}