// Code generated by sqlgen, version v1.0.0-alpha. DO NOT EDIT.

package customdeclare

import (
	"github.com/si3nloong/sqlgen/sequel/types"
)

func (v A) CreateTableStmt() string {
	return "CREATE TABLE IF NOT EXISTS " + v.TableName() + " (`name` VARCHAR(255) NOT NULL);"
}
func (A) AlterTableStmt() string {
	return "ALTER TABLE `a` MODIFY `name` VARCHAR(255) NOT NULL;"
}
func (A) InsertVarStmt() string {
	return "(?)"
}
func (A) Columns() []string {
	return []string{"`name`"}
}
func (v A) Values() []any {
	return []any{string(v.Name)}
}
func (v *A) Addrs() []any {
	return []any{types.String(&v.Name)}
}
