// Code generated by sqlgen. DO NOT EDIT.

package imported

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/si3nloong/sqlgen/sequel"
	"github.com/si3nloong/sqlgen/sequel/encoding"
)

func (Model) TableName() string {
	return "model"
}
func (Model) Columns() []string {
	return []string{"str", "bool", "raw_bytes", "int_16", "int_32", "int_64", "float_64", "time"} // 8
}
func (v Model) Values() []any {
	return []any{
		v.Str,      // 0 - str
		v.Bool,     // 1 - bool
		v.RawBytes, // 2 - raw_bytes
		v.Int16,    // 3 - int_16
		v.Int32,    // 4 - int_32
		v.Int64,    // 5 - int_64
		v.Float64,  // 6 - float_64
		v.Time,     // 7 - time
	}
}
func (v *Model) Addrs() []any {
	return []any{
		&v.Str,  // 0 - str
		&v.Bool, // 1 - bool
		encoding.StringScanner[sql.RawBytes](&v.RawBytes), // 2 - raw_bytes
		&v.Int16,   // 3 - int_16
		&v.Int32,   // 4 - int_32
		&v.Int64,   // 5 - int_64
		&v.Float64, // 6 - float_64
		&v.Time,    // 7 - time
	}
}
func (Model) SQLInsertPlaceholders(row int) string {
	return "(?,?,?,?,?,?,?,?)" // 8
}
func (v Model) InsertOneStmt() (string, []any) {
	return "INSERT INTO `model` (`str`,`bool`,`raw_bytes`,`int_16`,`int_32`,`int_64`,`float_64`,`time`) VALUES (?,?,?,?,?,?,?,?);", v.Values()
}
func (v Model) StrValue() any {
	return v.Str
}
func (v Model) BoolValue() any {
	return v.Bool
}
func (v Model) RawBytesValue() any {
	return v.RawBytes
}
func (v Model) Int16Value() any {
	return v.Int16
}
func (v Model) Int32Value() any {
	return v.Int32
}
func (v Model) Int64Value() any {
	return v.Int64
}
func (v Model) Float64Value() any {
	return v.Float64
}
func (v Model) TimeValue() any {
	return v.Time
}
func (v Model) ColumnStr() sequel.ColumnClause[sql.NullString] {
	return sequel.ValueColumn("str", v.Str)
}
func (v Model) ColumnBool() sequel.ColumnClause[sql.NullBool] {
	return sequel.ValueColumn("bool", v.Bool)
}
func (v Model) ColumnRawBytes() sequel.ColumnConvertClause[sql.RawBytes] {
	return sequel.Column("raw_bytes", v.RawBytes, convertSqlRawBytesToValue)
}
func (v Model) ColumnInt16() sequel.ColumnClause[sql.NullInt16] {
	return sequel.ValueColumn("int_16", v.Int16)
}
func (v Model) ColumnInt32() sequel.ColumnClause[sql.NullInt32] {
	return sequel.ValueColumn("int_32", v.Int32)
}
func (v Model) ColumnInt64() sequel.ColumnClause[sql.NullInt64] {
	return sequel.ValueColumn("int_64", v.Int64)
}
func (v Model) ColumnFloat64() sequel.ColumnClause[sql.NullFloat64] {
	return sequel.ValueColumn("float_64", v.Float64)
}
func (v Model) ColumnTime() sequel.ColumnClause[sql.NullTime] {
	return sequel.ValueColumn("time", v.Time)
}

func (Some) TableName() string {
	return "some"
}
func (Some) Columns() []string {
	return []string{"id"} // 1
}
func (v Some) Values() []any {
	return []any{
		v.ID, // 0 - id
	}
}
func (v *Some) Addrs() []any {
	return []any{
		&v.ID, // 0 - id
	}
}
func (Some) SQLInsertPlaceholders(row int) string {
	return "(?)" // 1
}
func (v Some) InsertOneStmt() (string, []any) {
	return "INSERT INTO `some` (`id`) VALUES (?);", v.Values()
}
func (v Some) IDValue() any {
	return v.ID
}
func (v Some) ColumnID() sequel.ColumnClause[uuid.UUID] {
	return sequel.ValueColumn("id", v.ID)
}

func convertSqlRawBytesToValue(val sql.RawBytes) any {
	return val
}
