// Code generated by sqlgen. DO NOT EDIT.

package array

import (
	"github.com/si3nloong/sqlgen/sequel"
	"github.com/si3nloong/sqlgen/sequel/encoding"
)

func (Array) TableName() string {
	return "array"
}
func (Array) Columns() []string {
	return []string{"tuple", "runes", "bytes", "fixed_size", "str"} // 5
}
func (v Array) Values() []any {
	return []any{
		v.Tuple[:],                // 0 - tuple
		string(v.Runes[:]),        // 1 - runes
		v.Bytes[:],                // 2 - bytes
		v.FixedSize[:],            // 3 - fixed_size
		encoding.JSONValue(v.Str), // 4 - str
	}
}
func (v *Array) Addrs() []any {
	return []any{
		encoding.ByteArrayScanner(v.Tuple[:], 2),      // 0 - tuple
		encoding.RuneArrayScanner(v.Runes[:], 4),      // 1 - runes
		encoding.ByteArrayScanner(v.Bytes[:], 10),     // 2 - bytes
		encoding.ByteArrayScanner(v.FixedSize[:], 10), // 3 - fixed_size
		encoding.JSONScanner(&v.Str),                  // 4 - str
	}
}
func (Array) InsertPlaceholders(row int) string {
	return "(?,?,?,?,?)" // 5
}
func (v Array) InsertOneStmt() (string, []any) {
	return "INSERT INTO `array` (`tuple`,`runes`,`bytes`,`fixed_size`,`str`) VALUES (?,?,?,?,?);", v.Values()
}
func (v Array) TupleValue() any {
	return v.Tuple[:]
}
func (v Array) RunesValue() any {
	return string(v.Runes[:])
}
func (v Array) BytesValue() any {
	return v.Bytes[:]
}
func (v Array) FixedSizeValue() any {
	return v.FixedSize[:]
}
func (v Array) StrValue() any {
	return encoding.JSONValue(v.Str)
}
func (v Array) ColumnTuple() sequel.ColumnConvertClause[[2]byte] {
	return sequel.Column("tuple", v.Tuple, func(val [2]byte) any {
		return val[:]
	})
}
func (v Array) ColumnRunes() sequel.ColumnConvertClause[[4]rune] {
	return sequel.Column("runes", v.Runes, func(val [4]rune) any {
		return string(val[:])
	})
}
func (v Array) ColumnBytes() sequel.ColumnConvertClause[[10]byte] {
	return sequel.Column("bytes", v.Bytes, func(val [10]byte) any {
		return val[:]
	})
}
func (v Array) ColumnFixedSize() sequel.ColumnConvertClause[[10]byte] {
	return sequel.Column("fixed_size", v.FixedSize, func(val [10]byte) any {
		return val[:]
	})
}
func (v Array) ColumnStr() sequel.ColumnConvertClause[[100]Str] {
	return sequel.Column("str", v.Str, func(val [100]Str) any {
		return encoding.JSONValue(val)
	})
}
