// Code generated by sqlgen, version 1.0.0. DO NOT EDIT.

package schema

import (
	"database/sql"
	"database/sql/driver"
)

func (A) Table() string {
	return "Apple"
}

func (A) Columns() []string {
	return []string{"id", "created_at"}
}

func (v A) Values() []any {
	return []any{v.ID, v.CreatedAt}
}

func (v *A) Addrs() []any {
	return []any{&v.ID, &v.CreatedAt}
}

func (B) Table() string {
	return "b"
}

func (B) Columns() []string {
	return []string{"id", "created_at"}
}

func (v B) Values() []any {
	return []any{v.ID, v.CreatedAt}
}

func (v *B) Addrs() []any {
	return []any{&v.ID, &v.CreatedAt}
}

func (C) Table() string {
	return "c"
}

func (C) Columns() []string {
	return []string{"id"}
}

func (C) IsAutoIncr() bool {
	return false
}

func (v C) PK() (int, any) {
	return 0, v.ID
}

func (v C) Values() []any {
	return []any{v.ID}
}

func (v *C) Addrs() []any {
	return []any{&v.ID}
}

func (D) Table() string {
	return "d"
}

func (D) Columns() []string {
	return []string{"id"}
}

func (D) IsAutoIncr() bool {
	return false
}

func (v D) PK() (int, any) {
	return 0, ((driver.Valuer)(v.ID))
}

func (v D) Values() []any {
	return []any{(driver.Valuer)(v.ID)}
}

func (v *D) Addrs() []any {
	return []any{(sql.Scanner)(&v.ID)}
}
