name: Test
on: push

jobs:
  test:
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        go: ["1.21"]
    runs-on: ${{ matrix.os }}
    # continue-on-error: false
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Get dependencies
        run: |
          go mod download

      - name: Test
        run: |
          go test ./examples/testdata_test.go
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      # - name: Golint
      #   run: |
      #     curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.10.2
      #     go get -u golang.org/x/lint/golint
      #     golangci-lint run
      #     golint -set_exit_status
