// Code generated by sqlgen, version v1.0.0-alpha. DO NOT EDIT.

package nopk

import (
	"github.com/si3nloong/sqlgen/sequel/types"
)

func (Customer) CreateTableStmt() string {
	return "CREATE TABLE IF NOT EXISTS `customer` (`name` VARCHAR(255) NOT NULL,`age` TINYINT UNSIGNED NOT NULL,`married` TINYINT NOT NULL);"
}
func (Customer) AlterTableStmt() string {
	return "ALTER TABLE `customer` MODIFY `name` VARCHAR(255) NOT NULL,MODIFY `age` TINYINT UNSIGNED NOT NULL AFTER `name`,MODIFY `married` TINYINT NOT NULL AFTER `age`;"
}
func (Customer) TableName() string {
	return "`customer`"
}
func (Customer) Columns() []string {
	return []string{"`name`", "`age`", "`married`"}
}
func (v Customer) Values() []any {
	return []any{string(v.Name), int64(v.Age), bool(v.Married)}
}
func (v *Customer) Addrs() []any {
	return []any{types.String(&v.Name), types.Integer(&v.Age), types.Bool(&v.Married)}
}
